# Before running the script, define the col-active and col-foreground variables like shown below, adjust to your liking

col-foreground: &col-foreground 66666CFF
col-active: &col-active DCD7BAff

bar:
  height: 26
  location: top
  spacing: 5
  margin: 7
 
  background: 111111cc
  foreground: *col-foreground

  left:
    - script:
            #path: ~/.config/yambar/yamscript.sh
            path: ~/.config/yambar/workspaces/script.sh
            args: [] 
            content:
              map:
                conditions:
                  workspace == 1:
                    - string: {text: " 1",foreground: *col-active} 
                    - string: {text: " 2",foreground: *col-foreground}
                    - string: {text: " 3",foreground: *col-foreground}
                    - string: {text: " 4",foreground: *col-foreground}
                    - string: {text: " 5",foreground: *col-foreground}
                    - string: {text: " 6",foreground: *col-foreground}
                    - string: {text: " 7",foreground: *col-foreground}
                    - string: {text: " 8",foreground: *col-foreground}
                    - string: {text: " 9",foreground: *col-foreground}
                    - string: {text: " 10",foreground: *col-foreground}
                  workspace == 2:
                    - string: {text: " 1",foreground: *col-foreground}
                    - string: {text: " 2",foreground: *col-active}
                    - string: {text: " 3",foreground: *col-foreground}
                    - string: {text: " 4",foreground: *col-foreground}
                    - string: {text: " 5",foreground: *col-foreground}
                    - string: {text: " 6",foreground: *col-foreground}
                    - string: {text: " 7",foreground: *col-foreground}
                    - string: {text: " 8",foreground: *col-foreground}
                    - string: {text: " 9",foreground: *col-foreground}
                    - string: {text: " 10",foreground: *col-foreground}
                  workspace == 3:
                    - string: {text: " 1",foreground: *col-foreground}
                    - string: {text: " 2",foreground: *col-foreground}
                    - string: {text: " 3",foreground: *col-active}
                    - string: {text: " 4",foreground: *col-foreground}
                    - string: {text: " 5",foreground: *col-foreground}
                    - string: {text: " 6",foreground: *col-foreground}
                    - string: {text: " 7",foreground: *col-foreground}
                    - string: {text: " 8",foreground: *col-foreground}
                    - string: {text: " 9",foreground: *col-foreground}
                    - string: {text: " 10",foreground: *col-foreground}
                  workspace == 4:
                    - string: {text: " 1",foreground: *col-foreground}
                    - string: {text: " 2",foreground: *col-foreground}
                    - string: {text: " 3",foreground: *col-foreground}
                    - string: {text: " 4",foreground: *col-active}
                    - string: {text: " 5",foreground: *col-foreground}
                    - string: {text: " 6",foreground: *col-foreground}
                    - string: {text: " 7",foreground: *col-foreground}
                    - string: {text: " 8",foreground: *col-foreground}
                    - string: {text: " 9",foreground: *col-foreground}
                    - string: {text: " 10",foreground: *col-foreground}
                  workspace == 5:
                    - string: {text: " 1",foreground: *col-foreground}
                    - string: {text: " 2",foreground: *col-foreground}
                    - string: {text: " 3",foreground: *col-foreground}
                    - string: {text: " 4",foreground: *col-foreground}
                    - string: {text: " 5",foreground: *col-active}
                    - string: {text: " 6",foreground: *col-foreground}
                    - string: {text: " 7",foreground: *col-foreground}
                    - string: {text: " 8",foreground: *col-foreground}
                    - string: {text: " 9",foreground: *col-foreground}
                    - string: {text: " 10",foreground: *col-foreground}
                  workspace == 6:
                    - string: {text: " 1",foreground: *col-foreground}
                    - string: {text: " 2",foreground: *col-foreground}
                    - string: {text: " 3",foreground: *col-foreground}
                    - string: {text: " 4",foreground: *col-foreground}
                    - string: {text: " 5",foreground: *col-foreground}
                    - string: {text: " 6",foreground: *col-active}
                    - string: {text: " 7",foreground: *col-foreground}
                    - string: {text: " 8",foreground: *col-foreground}
                    - string: {text: " 9",foreground: *col-foreground}
                    - string: {text: " 10",foreground: *col-foreground}
                  workspace == 7:
                    - string: {text: " 1",foreground: *col-foreground}
                    - string: {text: " 2",foreground: *col-foreground}
                    - string: {text: " 3",foreground: *col-foreground}
                    - string: {text: " 4",foreground: *col-foreground}
                    - string: {text: " 5",foreground: *col-foreground}
                    - string: {text: " 6",foreground: *col-foreground}
                    - string: {text: " 7",foreground: *col-active}
                    - string: {text: " 8",foreground: *col-foreground}
                    - string: {text: " 9",foreground: *col-foreground}
                    - string: {text: " 10",foreground: *col-foreground}
                  workspace == 8:
                    - string: {text: " 1",foreground: *col-foreground}
                    - string: {text: " 2",foreground: *col-foreground}
                    - string: {text: " 3",foreground: *col-foreground}
                    - string: {text: " 4",foreground: *col-foreground}
                    - string: {text: " 5",foreground: *col-foreground}
                    - string: {text: " 6",foreground: *col-foreground}
                    - string: {text: " 7",foreground: *col-foreground}
                    - string: {text: " 8",foreground: *col-active}
                    - string: {text: " 9",foreground: *col-foreground}
                    - string: {text: " 10",foreground: *col-foreground}
                  workspace == 9:
                    - string: {text: " 1",foreground: *col-foreground}
                    - string: {text: " 2",foreground: *col-foreground}
                    - string: {text: " 3",foreground: *col-foreground}
                    - string: {text: " 4",foreground: *col-foreground}
                    - string: {text: " 5",foreground: *col-foreground}
                    - string: {text: " 6",foreground: *col-foreground}
                    - string: {text: " 7",foreground: *col-foreground}
                    - string: {text: " 8",foreground: *col-foreground}
                    - string: {text: " 9",foreground: *col-active}
                    - string: {text: " 10",foreground: *col-foreground}
                  workspace == 10:
                    - string: {text: " 1",foreground: *col-foreground}
                    - string: {text: " 2",foreground: *col-foreground}
                    - string: {text: " 3",foreground: *col-foreground}
                    - string: {text: " 4",foreground: *col-foreground}
                    - string: {text: " 5",foreground: *col-foreground}
                    - string: {text: " 6",foreground: *col-foreground}
                    - string: {text: " 7",foreground: *col-foreground}
                    - string: {text: " 8",foreground: *col-foreground}
                    - string: {text: " 9",foreground: *col-foreground}
                    - string: {text: " 10",foreground: *col-active}
  right:
    - battery:
        name: BAT0
        poll-interval: 30000
        content:
          string: {text: "BAT: {capacity}%"}
    - clock:
        time-format: "%H:%M %Z"
        content:
          string: {text: "{date} {time}"}




