#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "jokes.h"  // Include the header generated by awk

int main(void) {
    int count = sizeof(jokes) / sizeof(jokes[0]);

    if (count == 0) {
        printf("No jokes found!\n");
        return 0;
    }

    // Pick a random joke
    srand((unsigned int)time(NULL));
    int choice = rand() % count;

    // Print joke, replacing "<>" with actual newlines
    const char *line = jokes[choice];
    while (*line) {
        if (*line == '<' && *(line + 1) == '>') {
            putchar('\n');
            line += 2;
        } else {
            putchar(*line++);
        }
    }
    putchar('\n');

    return 0;
}

